/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4/userguide/java_library_plugin.html
 */

group = "jdbc.stream"
version = "0.1.0"

plugins {
    `java-library`
	`maven-publish`
}

repositories {
    jcenter()
	mavenCentral()
}

dependencies {	
    testImplementation("junit:junit:4.12")
	testImplementation("org.xerial:sqlite-jdbc:3.27.2.1")
}

tasks {
    jar {
        manifest {
            attributes(
                mapOf("Implementation-Title" to project.name,
                      "Implementation-Version" to project.version)
            )
        }
    }
}